# Generated by Django 4.0.4 on 2022-05-05 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=65)),
                ('email', models.EmailField(max_length=254, verbose_name='mail del cliente')),
                ('fecha_contratacion', models.DateField(default=datetime.datetime)),
            ],
        ),
    ]
