# Generated by Django 4.0.4 on 2022-05-06 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_producto_alter_cliente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_contratacion',
            field=models.DateField(verbose_name=datetime.date(2022, 5, 5)),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
