# Generated by Django 4.0.4 on 2022-05-06 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_cliente_fecha_contratacion_delete_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_contratacion',
            field=models.DateField(verbose_name=datetime.date(2022, 5, 6)),
        ),
    ]
