# Generated by Django 4.0.4 on 2022-05-07 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_contratacion',
            field=models.DateField(verbose_name=datetime.date(2022, 5, 7)),
        ),
    ]
