# Generated by Django 4.0.4 on 2022-05-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_cliente_fecha_contratacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
