# Generated by Django 4.0.4 on 2022-05-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_alter_cliente_fecha_contratacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_contratacion',
            field=models.DateField(),
        ),
    ]
