# Generated by Django 4.0.4 on 2022-05-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_alter_cliente_fecha_contratacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='clave',
            field=models.CharField(blank='true', max_length=8, null='True'),
            preserve_default='True',
        ),
    ]
