# Generated by Django 4.0.4 on 2022-05-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_delete_producto_cliente_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.IntegerField(choices=[(1, 'Cliente'), (2, 'Administrador')], default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank='true', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(blank='true', null='True'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank='true', max_length=254, null='True', verbose_name='mail del cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_contratacion',
            field=models.DateField(blank='true', null='True'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank='true', max_length=50, null='True'),
        ),
    ]
